# Jekyll configuration for GitHub Pages
title: "Podcast Intelligence Hub"
description: "AI-powered podcast summaries and insights"
url: "https://USERNAME.github.io"  # Replace with your GitHub username
baseurl: "/podcast-summaries"      # Replace with your repo name

# Theme for mobile-friendly viewing
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Mobile-optimized settings
markdown: kramdown
highlighter: rouge

# Navigation
header_pages:
  - episodes.md
  - categories/ai.md
  - categories/crypto.md

# Collections for organized content
collections:
  episodes:
    output: true
    permalink: /:collection/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "episodes"
    values:
      layout: "episode"
  - scope:
      path: ""
    values:
      layout: "default"

# Exclude from processing
exclude:
  - scripts/
  - .github/